FROM gcr.io/cloud-builders/bazel

RUN apt-get update && apt-get install -y \
        zip \
	libxml2-dev \
	build-essential
lines (5 sloc)  124 Bytes
FROM gcr.io/cloud-builders/bazel

RUN apt-get update && apt-get install -y \
        zip \
	libxml2-dev \
	build-essential

